# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobmf_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_type',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Stock type'),
        ),
    ]
