# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import djangobmf.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangobmf_stock', '0002_stock_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproduct',
            name='price_currency',
            field=djangobmf.fields.CurrencyField(editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='price_precision',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
