# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobmf_stock', '0003_auto_20160624_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
